# Generated by Django 4.0.2 on 2022-02-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.CharField(max_length=200)),
                ('is_superuser', models.SmallIntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('fp_code', models.CharField(max_length=254)),
                ('is_staff', models.SmallIntegerField()),
                ('is_active', models.SmallIntegerField()),
                ('date_joined', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conversions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('from_id', models.CharField(max_length=10)),
                ('to_id', models.CharField(max_length=10)),
                ('rate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('user_id', models.CharField(max_length=254)),
                ('shortname', models.CharField(max_length=10)),
                ('is_active', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('number_of_students', models.CharField(max_length=50)),
                ('rp_name', models.CharField(max_length=150)),
                ('rp_signature', models.CharField(max_length=250)),
                ('rp_signature_file', models.CharField(max_length=50)),
                ('rp_signature_date', models.CharField(max_length=50)),
                ('principal_name', models.CharField(max_length=150)),
                ('principal_signature', models.CharField(max_length=50)),
                ('principal_signature_file', models.CharField(max_length=50)),
                ('principal_signature_date', models.CharField(max_length=50)),
                ('created_at', models.CharField(default='2022-14-02 05:49:37.530769', max_length=50)),
            ],
        ),
    ]
