# Generated by Django 4.0.2 on 2022-02-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=11)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.CharField(max_length=80)),
                ('profile_pic', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='schools',
            name='created_at',
            field=models.CharField(default='2022-16-02 15:17:23.698621', max_length=50),
        ),
    ]
