# Generated by Django 4.0.2 on 2022-02-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_children_alter_schools_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_pic',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='schools',
            name='created_at',
            field=models.CharField(default='2022-18-02 05:24:27.237586', max_length=50),
        ),
    ]
