# Generated by Django 4.0.2 on 2022-02-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_users_profile_pic_alter_schools_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_id', models.CharField(max_length=11)),
                ('reward_task_title', models.CharField(max_length=255)),
                ('reward_task_amount', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='schools',
            name='created_at',
            field=models.CharField(default='2022-19-02 10:29:09.766519', max_length=50),
        ),
    ]
