# Generated by Django 4.0.2 on 2022-02-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_schools_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=11)),
                ('child_id', models.CharField(max_length=255)),
                ('ts_title', models.CharField(max_length=255)),
                ('ts_amount', models.CharField(max_length=255)),
                ('ts_date', models.CharField(default='2022-22-02 19:26:28.181610', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='schools',
            name='created_at',
            field=models.CharField(default='2022-22-02 19:26:28.182607', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_joined',
            field=models.CharField(default='2022-22-02 19:26:28.178642', max_length=200),
        ),
    ]
